browser:
  browserName: chrome
  attachScreenshot: true
  headlessMode: true
  timeout: 10
environment:
  appUrl: http://146.59.32.4/index.php
  title: Home
testData:
  email: emilia.kowalska@wp.pl
  password: K0W4lski
  state: Arizona
  country: United States
  searchInput: HUMMINGBIRD
  paymentOption: Pay by Check
  statusLabel: Awaiting check payment
  confirmationMessage: YOUR ORDER IS CONFIRMED
  currencySymbol: $
  minimumFilterPrice: 9.00
  maximumFilterPrice: 11.00
  productForCart: THE BEST IS YET POSTER
  quantityForProduct: 3
  rangeOfQuantity: 5
  numberOfProductsAddedToCart: 5


