browser:
  browserName: chrome
  attachScreenshot: true
  headlessMode: true
  timeout: 30
environment:
  appUrl: http://146.59.32.4/index.php
  title: Home
testData:
  email: emilia.kowalska@wp.pl
  password: K0W4lski
  searchInput: HUMMINGBIRD
  currencySymbol: $
  priceFilterTag: $9.00 - $11.00
