browser:
  browserName: chrome
  attachScreenshot: true
  headlessMode: true
  timeout: 10
environment:
  appUrl: http://146.59.32.4/index.php
  title: Home
testData:
  email: emilia.kowalska@wp.pl
  password: K0W4lski
  searchInput: HUMMINGBIRD
  currencySymbol: $
  minimumFilterPrice: 9.00
  maximumFilterPrice: 11.00


