browser:
  browserName: chrome
  attachScreenshot: true
  headlessMode: true
  timeout: 10
environment:
  appUrl: https://www.filmweb.pl
  title: Filmweb - filmy takie jak Ty!
testData:
  username: Piter
  password: Kowalski
  searchInput: HUMMINGBIRD
